In [30]:

import sys

sys.path.append("/home/jovyan/work")

import src.configuracion_ia as cia

## Chatear

In [34]:
print("¡Hola! ¡Soy el Agente BiblioIA!")
print("Escribí 'salir' para terminar.")
print("-" * 60)

while True:
    pregunta = input("\nIngresá tu pregunta:\n > ")

    if pregunta.lower() in [
        'salir', 'chau', 'adios',
        'adiós', 'exit', 'quit'
    ]:
        print("¡Nos vemos!")
        break

    if not pregunta.strip():
        continue

    cia.preguntar_al_agente(pregunta)

¡Hola! ¡Soy el Agente BiblioIA!
Escribí 'salir' para terminar.
------------------------------------------------------------
Pregunta del usuario:
> pasame el isbn del libro con mas ejemplares

SQL GENERADO:
 SELECT isbn
FROM ejemplar
GROUP BY isbn
ORDER BY COUNT(nro_ejemplar) DESC
LIMIT 1

Conectando a la base de datos...
Resultado:

                isbn
0  978-01-43433-88-8

Pregunta del usuario:
> pasame la cantidad de ejemplares disponibles con isbn 978-01-43433-88-8

SQL GENERADO:
 SELECT COUNT(*)
FROM ejemplar e
WHERE e.isbn = '978-01-43433-88-8' AND e.id_estadoFisico = 1

Conectando a la base de datos...
Resultado:

   COUNT(*)
0         2

¡Nos vemos!

## Sección de pruebas

In [ ]:
print("Preguntas de prueba")
print("=" * 60)
preguntas_minimas = [
    "¿Cuáles son los 5 libros más prestados este año?",
    "¿Qué socios tienen préstamos vencidos en este momento?",
    "¿Cuántos ejemplares disponibles hay del libro con ISBN 978-01-43433-88-8?",
    "¿Qué libros de Derecho están disponibles para prestar?",
    "¿Cuál es el historial de préstamos del socio con DNI 47910299?",
    "¿Qué autores tienen más de 3 libros en la biblioteca?",
    "¿Cuántas sanciones se generaron en el último mes?"
]

preguntas_adicionales = [
    "¿Qué socios tienen más de 3 préstamos históricos?",
    "¿Cuáles son los 3 libros más prestados de medicina?",
    "¿Cuál es el libro con mayor cantidad de ejemplares?"
]

print("=" * 60)
print("Preguntas mínimas")
print("=" * 60)
for p in preguntas_minimas:
    cia.preguntar_al_agente(p)
    print("-" * 60)


print("=" * 60)
print("Preguntas adicionales")
print("=" * 60)
for p in preguntas_adicionales:
    cia.preguntar_al_agente(p)
    print("-" * 60)

    
print("Listo!")

Preguntas de prueba
============================================================
============================================================
Preguntas mínimas
============================================================
Pregunta del usuario:
> ¿Cuáles son los 5 libros más prestados este año?

SQL GENERADO:
 SELECT l.isbn, l.titulo, COUNT(p.id_prestamo) AS total_prestamos
FROM libro l
JOIN ejemplar e ON l.isbn = e.isbn
JOIN prestamo p ON e.id_ejemplar = p.id_ejemplar
WHERE YEAR(p.fecha_prestamo) = YEAR(CURDATE())
GROUP BY l.isbn, l.titulo
ORDER BY total_prestamos DESC
LIMIT 5;

Conectando a la base de datos...
Resultado:

,isbn,titulo,total_prestamos
0,978-11-99367-49-3,Semántica y pragmática del lenguaje natural,9
1,978-69-67717-33-9,Infecciones virales: epidemiología y control,9
2,978-39-60747-13-4,Antropología cultural: rituales y tradiciones,8
3,978-37-54328-83-4,Derecho internacional público y privado,7
4,978-10-01547-86-8,La violencia política en Occidente contemporáneo,6

------------------------------------------------------------
Pregunta del usuario:
> ¿Qué socios tienen préstamos vencidos en este momento?

SQL GENERADO:
 SELECT DISTINCT s.id_socio, s.nombre, s.apellido
FROM socio s
JOIN prestamo p ON s.id_socio = p.id_socio
WHERE p.fecha_vencimiento < CURDATE() AND p.fecha_devolucion IS NULL;

Conectando a la base de datos...
Resultado:

       apellido  id_socio      nombre
0        Islami       285  Habibullah
1         Čubro       914    Tsimafei
2        Duncan       393       Naser
3     Al Shamsi       649    Zacharie
4        Mishra       639      Brayan
..          ...       ...         ...
622      Ghanem       442   Stéphanie
623     Teodoro       152      Adrian
624  Nesterenko       139         Thu
625         Kam       157       Grace
626    Claverol        62    Xiaojuan

[627 rows x 3 columns]

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuántos ejemplares disponibles hay del libro con ISBN 978-01-43433-88-8?

SQL GENERADO:
 SELECT COUNT(e.id_ejemplar)
FROM ejemplar e
WHERE e.isbn = '978-01-43433-88-8' AND e.id_estadoFisico = 1

Conectando a la base de datos...
Resultado:

   COUNT(e.id_ejemplar)
0                     2

------------------------------------------------------------
Pregunta del usuario:
> ¿Qué libros de ciencia ficción están disponibles para prestar?

SQL GENERADO:
 SELECT l.isbn, l.titulo
FROM libro l
JOIN generoLibro gl
ON l.isbn = gl.isbn
JOIN genero g
ON gl.id_genero = g.id_genero
WHERE g.nombre = 'ciencia ficción'
AND l.stock_disponible > 0

Conectando a la base de datos...
Resultado:

Empty DataFrame
Columns: []
Index: []

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuál es el historial de préstamos del socio con DNI 47910299?

Ocurrió un error:
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvdy3frzftp8fm63jxvafwke` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99696, Requested 1034. Please try again in 10m30.72s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

------------------------------------------------------------
Pregunta del usuario:
> ¿Qué autores tienen más de 3 libros en la biblioteca?

Ocurrió un error:
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvdy3frzftp8fm63jxvafwke` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99696, Requested 1028. Please try again in 10m25.536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuántas sanciones se generaron en el último mes?

Ocurrió un error:
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvdy3frzftp8fm63jxvafwke` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99696, Requested 1028. Please try again in 10m25.536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

------------------------------------------------------------
============================================================
Preguntas adicionales
============================================================
Pregunta del usuario:
> ¿Qué socios tienen más de 3 préstamos históricos?

Ocurrió un error:
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvdy3frzftp8fm63jxvafwke` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99696, Requested 1029. Please try again in 10m26.4s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuáles son los 3 libros más prestados de medicina?

Ocurrió un error:
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvdy3frzftp8fm63jxvafwke` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99695, Requested 1029. Please try again in 10m25.536s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuál es el libro con mayor cantidad de ejemplares?

Ocurrió un error:
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kvdy3frzftp8fm63jxvafwke` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99695, Requested 1027. Please try again in 10m23.808s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}

------------------------------------------------------------
Listo!

In [7]:
print("Prueba rápida de IA")
print("-" * 60)

# preguntar_al_agente("cuáles son los 10 libros más prestados de medicina?")
# preguntar_al_agente("Hola!")
cia.preguntar_al_agente("Qué socios tienen más de 3 préstamos históricos? ordenados de mayo a menor")

Prueba rápida de IA
------------------------------------------------------------
Pregunta del usuario:
> Qué socios tienen más de 3 préstamos históricos? ordenados de mayo a menor

SQL Generado por el modelo:
SQL GENERADO:
 SELECT s.id_socio, s.nombre, s.apellido, COUNT(p.id_prestamo) AS total_prestamos
FROM socio s
JOIN prestamo p
ON s.id_socio = p.id_socio
GROUP BY s.id_socio, s.nombre, s.apellido
HAVING COUNT(p.id_prestamo) > 3
ORDER BY total_prestamos DESC;
DEBUG SQL: 'SELECT s.id_socio, s.nombre, s.apellido, COUNT(p.id_prestamo) AS total_prestamos \nFROM socio s \nJOIN prestamo p \nON s.id_socio = p.id_socio \nGROUP BY s.id_socio, s.nombre, s.apellido \nHAVING COUNT(p.id_prestamo) > 3 \nORDER BY total_prestamos DESC;'


Conectando a la base de datos...
Resultado:

     id_socio    nombre   apellido  total_prestamos
0         862     Vaine   Malmgren               11
1         332      Nils   Thongsri               11
2         941   Josette  Hernández               10
3         971    Bessem        Hoi                9
4         715  Isabella      Soler                9
..        ...       ...        ...              ...
356       967     Sarai     Yassin                4
357       486       Luz      Young                4
358        22    Sering     Yousef                4
359       161    Savvas     Zamore                4
360       988   Madison       Zidi                4

[361 rows x 4 columns]

In [ ]:
try:
    res = requests.post(llm_url, 
                        json={"model": "llama3.2", "prompt": "Hola, estás vivo?", "stream": False}, 
                        timeout=60)
    print("Respuesta de Ollama:", res.json()['response'])
except Exception as e:
    print("Error al conectar con Ollama:", e)