In [11]:

import sys

sys.path.append("/home/jovyan/work")

import src.configuracion_ia as cia

## Chatear

In [15]:
print("¡Hola! ¡Soy el Agente BiblioIA!")
print("Escribí 'salir' para terminar.")
print("-" * 60)

while True:
    pregunta = input("\nIngresá tu pregunta:\n > ")

    if pregunta.lower() in [
        'salir', 'chau', 'adios',
        'adiós', 'exit', 'quit'
    ]:
        print("¡Nos vemos!")
        break

    if not pregunta.strip():
        continue

    cia.preguntar_al_agente(pregunta)

¡Hola! ¡Soy el Agente BiblioIA!
Escribí 'salir' para terminar.
------------------------------------------------------------
Pregunta del usuario:
> recomendar 222

SQL Generado por el modelo:
SQL GENERADO:
 SELECT 'Lo siento, no puedo ayudarte con eso' AS mensaje_sistema;


Conectando a la base de datos...
Resultado:

                        mensaje_sistema
0  Lo siento, no puedo ayudarte con eso

¡Nos vemos!

## Sección de pruebas

In [12]:
print("Preguntas de prueba")
print("=" * 60)
preguntas_minimas = [
    "¿Cuáles son los 5 libros más prestados este año?",
    "¿Qué socios tienen préstamos vencidos en este momento?",
    "¿Cuántos ejemplares disponibles hay del libro con ISBN X?",
    "¿Qué libros de ciencia ficción están disponibles para prestar?",
    "¿Cuál es el historial de préstamos del socio con DNI Y?",
    "¿Qué autores tienen más de 3 libros en la biblioteca?",
    "¿Cuántas sanciones se generaron en el último mes?"
]

preguntas_adicionales = [
    "¿Qué socios tienen más de 3 préstamos históricos?",
    "¿Cuáles son los 3 libros más prestados de medicina?",
    "¿Cuál es el libro con mayor cantidad de ejemplares?"
]

print("=" * 60)
print("Preguntas mínimas")
print("=" * 60)
for p in preguntas_minimas:
    cia.preguntar_al_agente(p)
    print("-" * 60)


print("=" * 60)
print("Preguntas adicionales")
print("=" * 60)
for p in preguntas_adicionales:
    cia.preguntar_al_agente(p)
    print("-" * 60)

    
print("Listo!")

Preguntas de prueba
============================================================
============================================================
Preguntas mínimas
============================================================
Pregunta del usuario:
> ¿Cuáles son los 5 libros más prestados este año?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT l.isbn, l.titulo, COUNT(p.id_prestamo) AS total_prestamos
FROM libro l
JOIN ejemplar e ON l.isbn = e.isbn
JOIN prestamo p ON e.id_ejemplar = p.id_ejemplar
WHERE YEAR(p.fecha_prestamo) = YEAR(CURDATE())
GROUP BY l.isbn, l.titulo
ORDER BY total_prestamos DESC
LIMIT 5;


Conectando a la base de datos...
Resultado:

Empty DataFrame
Columns: []
Index: []

------------------------------------------------------------
Pregunta del usuario:
> ¿Qué socios tienen préstamos vencidos en este momento?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT s.id_socio, s.nombre, s.apellido
FROM socio s
JOIN prestamo p
ON s.id_socio = p.id_socio
WHERE p.fecha_vencimiento < CURDATE() AND p.fecha_devolucion IS NULL;


Conectando a la base de datos...
Resultado:

      apellido  id_socio      nombre
0       Islami       285  Habibullah
1        Čubro       914    Tsimafei
2       Duncan       393       Naser
3    Al Shamsi       649    Zacharie
4       Mishra       639      Brayan
..         ...       ...         ...
922    Salazar       834       Widad
923  Blanchard       810       Houda
924    Sweilem       708      Miriam
925   Figueroa       881       Teipo
926     Ghanem       442   Stéphanie

[927 rows x 3 columns]

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuántos ejemplares disponibles hay del libro con ISBN X?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT COUNT(e.id_ejemplar)
FROM ejemplar e
JOIN libro l
ON e.isbn = l.isbn
WHERE l.isbn = 'X' AND e.id_estadoFisico = 1;


Conectando a la base de datos...
Resultado:

   COUNT(e.id_ejemplar)
0                     0

------------------------------------------------------------
Pregunta del usuario:
> ¿Qué libros de ciencia ficción están disponibles para prestar?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT l.isbn, l.titulo
FROM libro l
JOIN generoLibro gl
ON l.isbn = gl.isbn
JOIN genero g
ON gl.id_genero = g.id_genero
WHERE g.nombre = 'ciencia ficción'
AND l.stock_disponible > 0


Conectando a la base de datos...
Resultado:

Empty DataFrame
Columns: []
Index: []

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuál es el historial de préstamos del socio con DNI Y?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT p.fecha_prestamo, p.fecha_vencimiento, p.fecha_devolucion, l.titulo
FROM prestamo p
JOIN ejemplar e ON p.id_ejemplar = e.id_ejemplar
JOIN libro l ON e.isbn = l.isbn
JOIN socio s ON p.id_socio = s.id_socio
WHERE s.dni = 'Y'


Conectando a la base de datos...
Resultado:

Empty DataFrame
Columns: []
Index: []

------------------------------------------------------------
Pregunta del usuario:
> ¿Qué autores tienen más de 3 libros en la biblioteca?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT a.nombre, a.apellido, COUNT(DISTINCT la.isbn) AS cantidad_libros
FROM autor a
JOIN libroAutor la
ON a.id_autor = la.id_autor
GROUP BY a.id_autor, a.nombre, a.apellido
HAVING COUNT(DISTINCT la.isbn) > 3;


Conectando a la base de datos...
Resultado:

      apellido  cantidad_libros     nombre
0          Lai                5    Matthew
1   Barrientos                4     Andrea
2        Macia                5     Martin
3    Hyppolite                4      Alain
4       Volkov                5     Ignace
..         ...              ...        ...
80    Celestin                8      Moosa
81      Khamis                4      Josef
82        Naji                6  Catherine
83     Barthel                4     'Alisi
84    Brajović                7    Bangura

[85 rows x 3 columns]

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuántas sanciones se generaron en el último mes?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT COUNT(*)
FROM sancion s
WHERE s.fecha_inicio >= NOW() - INTERVAL 1 MONTH


Conectando a la base de datos...
Resultado:

   COUNT(*)
0         0

------------------------------------------------------------
============================================================
Preguntas adicionales
============================================================
Pregunta del usuario:
> ¿Qué socios tienen más de 3 préstamos históricos?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT s.id_socio, s.nombre, s.apellido, COUNT(p.id_prestamo) AS total_prestamos
FROM socio s
JOIN prestamo p
ON s.id_socio = p.id_socio
GROUP BY s.id_socio, s.nombre, s.apellido
HAVING COUNT(p.id_prestamo) > 3;


Conectando a la base de datos...
Resultado:

         apellido  id_socio   nombre  total_prestamos
0          Abbott       557     Hawa                5
1    Abdrakhmanov       147   Tehani                5
2          Adkins       775   Kahsay                5
3           Ahmed       617    Tomáš                6
4            Akel       611    Ogola                5
..            ...       ...      ...              ...
356        Yassin       967    Sarai                4
357         Young       486      Luz                4
358        Yousef        22   Sering                4
359        Zamore       161   Savvas                4
360          Zidi       988  Madison                4

[361 rows x 4 columns]

------------------------------------------------------------
Pregunta del usuario:
> ¿Cuáles son los 3 libros más prestados de medicina?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT l.isbn, l.titulo, la.nombre, COUNT(p.id_prestamo) AS total_prestamos
FROM libro l
JOIN generoLibro gl ON l.isbn = gl.isbn
JOIN genero g ON gl.id_genero = g.id_genero
JOIN ejemplar e ON l.isbn = e.isbn
JOIN prestamo p ON e.id_ejemplar = p.id_ejemplar
JOIN libroAutor la ON l.isbn = la.isbn
WHERE g.nombre = 'medicina'
GROUP BY l.isbn, l.titulo, la.nombre
ORDER BY total_prestamos DESC
LIMIT 3;


Conectando a la base de datos...
Ocurrió un error:
(mysql.connector.errors.ProgrammingError) 1054 (42S22): Unknown column 'la.nombre' in 'field list'
[SQL: SELECT l.isbn, l.titulo, la.nombre, COUNT(p.id_prestamo) AS total_prestamos
FROM libro l
JOIN generoLibro gl ON l.isbn = gl.isbn
JOIN genero g ON gl.id_genero = g.id_genero
JOIN ejemplar e ON l.isbn = e.isbn
JOIN prestamo p ON e.id_ejemplar = p.id_ejemplar
JOIN libroAutor la ON l.isbn = la.isbn
WHERE g.nombre = 'medicina'
GROUP BY l.isbn, l.titulo, la.nombre
ORDER BY total_prestamos DESC
LIMIT 3;]
(Background on this error at: https://sqlalche.me/e/20/f405)


------------------------------------------------------------
Pregunta del usuario:
> ¿Cuál es el libro con mayor cantidad de ejemplares?

SQL Generado por el modelo:
SQL GENERADO:
 SELECT l.titulo, e.nro_ejemplar
FROM libro l
JOIN ejemplar e
ON l.isbn = e.isbn
GROUP BY l.titulo
ORDER BY COUNT(e.nro_ejemplar) DESC
LIMIT 1;


Conectando a la base de datos...
Ocurrió un error:
(mysql.connector.errors.ProgrammingError) 1055 (42000): Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'defaultdb.e.nro_ejemplar' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
[SQL: SELECT l.titulo, e.nro_ejemplar
FROM libro l
JOIN ejemplar e
ON l.isbn = e.isbn
GROUP BY l.titulo
ORDER BY COUNT(e.nro_ejemplar) DESC
LIMIT 1;]
(Background on this error at: https://sqlalche.me/e/20/f405)


------------------------------------------------------------
Listo!

In [7]:
print("Prueba rápida de IA")
print("-" * 60)

# preguntar_al_agente("cuáles son los 10 libros más prestados de medicina?")
# preguntar_al_agente("Hola!")
cia.preguntar_al_agente("Qué socios tienen más de 3 préstamos históricos? ordenados de mayo a menor")

Prueba rápida de IA
------------------------------------------------------------
Pregunta del usuario:
> Qué socios tienen más de 3 préstamos históricos? ordenados de mayo a menor

SQL Generado por el modelo:
SQL GENERADO:
 SELECT s.id_socio, s.nombre, s.apellido, COUNT(p.id_prestamo) AS total_prestamos
FROM socio s
JOIN prestamo p
ON s.id_socio = p.id_socio
GROUP BY s.id_socio, s.nombre, s.apellido
HAVING COUNT(p.id_prestamo) > 3
ORDER BY total_prestamos DESC;
DEBUG SQL: 'SELECT s.id_socio, s.nombre, s.apellido, COUNT(p.id_prestamo) AS total_prestamos \nFROM socio s \nJOIN prestamo p \nON s.id_socio = p.id_socio \nGROUP BY s.id_socio, s.nombre, s.apellido \nHAVING COUNT(p.id_prestamo) > 3 \nORDER BY total_prestamos DESC;'


Conectando a la base de datos...
Resultado:

     id_socio    nombre   apellido  total_prestamos
0         862     Vaine   Malmgren               11
1         332      Nils   Thongsri               11
2         941   Josette  Hernández               10
3         971    Bessem        Hoi                9
4         715  Isabella      Soler                9
..        ...       ...        ...              ...
356       967     Sarai     Yassin                4
357       486       Luz      Young                4
358        22    Sering     Yousef                4
359       161    Savvas     Zamore                4
360       988   Madison       Zidi                4

[361 rows x 4 columns]

In [ ]:
try:
    res = requests.post(llm_url, 
                        json={"model": "llama3.2", "prompt": "Hola, estás vivo?", "stream": False}, 
                        timeout=60)
    print("Respuesta de Ollama:", res.json()['response'])
except Exception as e:
    print("Error al conectar con Ollama:", e)